//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

namespace GAF
{
	public enum ObjectType
	{
		  Simple
		, Mask
		, Masked
	}

	public interface IGAFObject : IComparable
	{
		#region Base Methods

		void initialize(ObjectType _Type, GAFMovieClip _Player, GAFObjectsManager _Manager, string _Name, int _ObjectID, int _AtlasElementID);

		void reload(GAFRenderProcessor _Processor);

		void updateToState(GAFObjectStateData _State, GAFRenderProcessor _Processor, bool Refresh);

		#endregion // Base Methods

		#region Base Data

		int getID();

		string getName();

		GAFMovieClip getMovieClip();

		GAFObjectsManager getManager();

		Material getCurrentMaterial();

		Texture2D getTexture();

		int getAtlasElementID();

		GAFAtlasData getAtlasData();

		GAFAtlasElementData getAtlasElementData();

		GAFTexturesData getTexturesData();

		GAFObjectStateData getCurrentState();

		int getZOrder();

		Vector3 getLocalPosition();

		Vector3 getStatePosition();

		#endregion // Base Data

		#region Manipulators

		bool getVisible();

		void setVisible(bool _Visible);

		Vector2 getPositionOffset();

		void setPositionOffset(Vector2 _Offset);

		Material getCustomMaterial();

		void setCustomMaterial(Material _Material);

		#endregion // Manipulators
	}
}